os: osx
language: generic

# only build on tag releases
#if: tag IS present

jobs:
  include:
    - stage: Run Sylph on AWS Device Farms
      env: Run Sylph on AWS Device Farms
      before_install:

      # install correct version of java on osx to run sdkmanager
#      - java -version
#      - export HOMEBREW_NO_AUTO_UPDATE=1
#      - brew cask uninstall java; brew tap caskroom/versions; brew cask install java8;
#      - java -version

        # Add missing java module used by sdkmanager, etc...
      - export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'

      # Install android tools
      - ANDROID_SDK_TOOLS=4333796 # android-28
      - ANDROID_PLATFORM_SDK=28
      - ANDROID_BUILD_TOOLS=28.0.3
      - export ANDROID_HOME=~/android-sdk
      - wget -q "https://dl.google.com/android/repository/sdk-tools-darwin-$ANDROID_SDK_TOOLS.zip" -O android-sdk-tools.zip
      - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
      - rm android-sdk-tools.zip
      - PATH=${PATH}:${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
      # Silence warning.
      - mkdir -p ~/.android
      - touch ~/.android/repositories.cfg
      # Accept licenses before installing components, no need to echo y for each component
      - yes | sdkmanager --licenses
      - sdkmanager --list | head -15
      # Platform and build tools
      - sdkmanager "tools" "platform-tools" "platforms;android-${ANDROID_PLATFORM_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
      - sdkmanager --list | head -15

      # fix timezone warning on osx
      - sudo ln -sf /usr/share/zoneinfo/US/Pacific /etc/localtime

      # setup osx environment for flutter
#      - export HOMEBREW_NO_AUTO_UPDATE=1
#      - brew install libimobiledevice
#      - brew install ideviceinstaller
#      - brew install ios-deploy
#      - brew install cocoapods || echo 'ignore exit(1)'
#      - brew link --overwrite cocoapods

      # install pre-compiled flutter
      - FLUTTER_HOME=~
      - FLUTTER_CHANNEL=stable
      - FLUTTER_VERSION=1.2.1-${FLUTTER_CHANNEL}
      - wget --quiet --output-document=flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_v${FLUTTER_VERSION}.zip && unzip -qq flutter.zip -d ${FLUTTER_HOME}> /dev/null && rm flutter.zip
      - export PATH="$PATH":"$HOME/.pub-cache/bin"
      - export PATH=${FLUTTER_HOME}/flutter/bin:${FLUTTER_HOME}/flutter/bin/cache/dart-sdk/bin:$PATH
      - flutter doctor -v

      # install aws
      - (cd ~; curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"; unzip awscli-bundle.zip; sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws)
      - aws --version
      - cp -r .aws ~

      # install most current (released or unreleased) version of Sylph
      - (cd ~; git clone https://github.com/mmcc007/sylph.git; pub global activate --source path sylph)

      script:
        - ls -la
        - sylph

      # publish artifacts to GitHub
      before_deploy:
      # bundle artifacts for publishing
      - (cd /tmp; zip -r /tmp/sylph_artifacts.zip sylph_artifacts)
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: KzdPAQ9x5/WH8U2ICzVOlSNu0YThzERM4598n3p1YJgxtl5O4/rBsoIOktOMgy/u2drUnnOhqnTXc9NDDxfCBnVZ+JYT7vzjqxuFmOio2TgJbGAAmxM8fTt92m+xQ6hf24BUZTSDBQ3I0R+pr3Zx6D1Vi9sjvK6gNgGtR+A1G8/R+THECrXWWdWQLpGEuJ9cXFBvD1eeOZXNvrl2xmfBjMKF4HExAsxVmHjD8D6nUX8TN0QysZUP2LF02BdPDXvVt+dKMEU1DYIXi2bAVquSr86M2oTFSTMnJAhs1hBQZFWRn8G1NEitpW4Dnd0522MguVhds5bKHkaKBAd8ENJmOxhZ7ce77lV+veqGns/EN5776dpmmHzoMXgdFDDmIQYsaZNL4DSHYbL68Hkg2LcKSIS6GN+Fa1isu2lTvl11jkaHHeg4yrJ54xMByM45MiJ+3Wr293DJluIHL6fPvQvzR5zNMfhOZ0M9JqF5l6/4KupYyxByRmy5Cl3IpsvXFf4WhIZbgDI1dOZxzXYQ/xMcm9f9Jm8kPIy4gFzEZNcdfvtQ74zzUsmXjUz2/4qImimqens9XLXMeRCN+3I125xl9PlxGJfDVCJqNj3RX6QvmljjHHs7XyvUoHw2WhsfzLTusmzncIE44pXdsVQEpFsPBl/hi4RO/wh3sgw8z5Br/G0=
        file: /tmp/sylph_artifacts.zip
        on:
          tags: true
